using System;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace GDMember.CSharp;

[Generator(LanguageNames.CSharp)]
public sealed class GDMemberGenerator : IIncrementalGenerator
{
    private static readonly DiagnosticDescriptor InvalidDeclaration = new(
        "GDMEMBER001", "Invalid GDMember declaration", "{0}", "GDMember",
        DiagnosticSeverity.Error, isEnabledByDefault: true);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var methods = context.SyntaxProvider.ForAttributeWithMetadataName(
            "Moon.GDMemberAttribute",
            static (node, _) => node is MethodDeclarationSyntax,
            static (attribute, _) => Create(attribute));
        context.RegisterSourceOutput(methods, static (output, result) =>
        {
            if (result.Error is not null)
                output.ReportDiagnostic(Diagnostic.Create(InvalidDeclaration, result.Location, result.Error));
            else
                output.AddSource(result.HintName, result.Source!);
        });
    }

    private static Result Create(GeneratorAttributeSyntaxContext context)
    {
        var syntax = (MethodDeclarationSyntax)context.TargetNode;
        var method = (IMethodSymbol)context.TargetSymbol;
        Result Error(string message) => new("", null, message, syntax.GetLocation());

        if (!syntax.Modifiers.Any(SyntaxKind.PartialKeyword) || syntax.Body is not null || syntax.ExpressionBody is not null ||
            method.IsStatic || method.IsGenericMethod || method.ReturnsByRef || method.ReturnsByRefReadonly ||
            method.ExplicitInterfaceImplementations.Length > 0 ||
            syntax.Modifiers.Any(m => m.IsKind(SyntaxKind.AbstractKeyword) || m.IsKind(SyntaxKind.ExternKeyword)) ||
            !syntax.Ancestors().OfType<TypeDeclarationSyntax>().First().IsKind(SyntaxKind.ClassDeclaration))
            return Error("GDMember requires an instance, non-generic partial method declaration without a body in a class.");

        if (method.Parameters.Length > 16 || method.Parameters.Any(p => p.RefKind != RefKind.None || p.IsParams || p.HasExplicitDefaultValue) ||
            syntax.ParameterList.Parameters.Any(p => p.Modifiers.Count > 0))
            return Error("GDMember supports at most 16 ordinary typed parameters without modifiers or defaults.");

        var scopes = syntax.Ancestors().OfType<TypeDeclarationSyntax>().Reverse().ToArray();
        if (scopes.Any(scope => !scope.Modifiers.Any(SyntaxKind.PartialKeyword) || scope.Modifiers.Any(SyntaxKind.FileKeyword)))
            return Error("The containing class and all enclosing types must be partial and must not be file-local.");

        if (method.ContainingType.GetMembers(method.Name).OfType<IMethodSymbol>()
            .Count(m => m.GetAttributes().Any(a => a.AttributeClass?.ToDisplayString() == "Moon.GDMemberAttribute")) > 1)
            return Error($"Overloaded GDMember '{method.Name}' is not supported.");

        var fieldName = "_FSharpInvoke" + method.Name;
        if (method.ContainingType.GetMembers(fieldName).Length > 0)
            return Error($"The generated delegate field '{fieldName}' conflicts with an existing member.");

        var typeFormat = SymbolDisplayFormat.FullyQualifiedFormat.WithMiscellaneousOptions(
            SymbolDisplayFormat.FullyQualifiedFormat.MiscellaneousOptions | SymbolDisplayMiscellaneousOptions.IncludeNullableReferenceTypeModifier);
        var returnType = method.ReturnType.ToDisplayString(typeFormat);
        var parameterTypes = method.Parameters.Select(p => p.Type.ToDisplayString(typeFormat)).ToArray();
        var delegateType = method.ReturnsVoid
            ? parameterTypes.Length == 0 ? "global::System.Action" : $"global::System.Action<{string.Join(", ", parameterTypes)}>"
            : $"global::System.Func<{string.Join(", ", parameterTypes.Concat(new[] { returnType }))}>";
        var parameters = string.Join(", ", method.Parameters.Select((p, i) => parameterTypes[i] + " " + syntax.ParameterList.Parameters[i].Identifier.Text));
        var arguments = string.Join(", ", syntax.ParameterList.Parameters.Select(p => p.Identifier.Text));

        var builder = new StringBuilder("// <auto-generated />\n#nullable enable\n");
        if (!method.ContainingNamespace.IsGlobalNamespace)
            builder.Append("namespace ").Append(method.ContainingNamespace.ToDisplayString()).AppendLine(" {");
        foreach (var scope in scopes)
        {
            var kind = scope is RecordDeclarationSyntax record
                ? "record " + (record.ClassOrStructKeyword.IsKind(SyntaxKind.StructKeyword) ? "struct" : "class")
                : scope.Keyword.Text;
            builder.Append(string.Join(" ", scope.Modifiers.Select(m => m.Text))).Append(' ')
                .Append(kind).Append(' ').Append(scope.Identifier.Text).Append(scope.TypeParameterList?.ToString()).AppendLine(" {");
        }
        builder.Append("public ").Append(delegateType).Append("? ").Append(fieldName).AppendLine(";");
        builder.Append(string.Join(" ", syntax.Modifiers.Select(m => m.Text))).Append(' ')
            .Append(returnType).Append(' ').Append(syntax.Identifier.Text).Append('(').Append(parameters).AppendLine(")");
        if (method.ReturnsVoid)
            builder.Append("=> ").Append(fieldName).Append("?.Invoke(").Append(arguments).AppendLine(");");
        else
            builder.Append("=> (").Append(fieldName).Append(" ?? throw new global::System.InvalidOperationException(")
                .Append(SymbolDisplay.FormatLiteral($"F# GDMember '{method.Name}' has not been initialized.", quote: true))
                .Append("))(").Append(arguments).AppendLine(");");
        foreach (var _ in scopes)
            builder.AppendLine("}");
        if (!method.ContainingNamespace.IsGlobalNamespace)
            builder.AppendLine("}");

        var identity = method.ContainingType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat) + "." + method.Name;
        var hint = string.Concat(Encoding.UTF8.GetBytes(identity).Select(b => b.ToString("x2"))) + ".GDMember.g.cs";
        return new Result(hint, builder.ToString(), null, null);
    }

    private readonly struct Result : IEquatable<Result>
    {
        public Result(string hintName, string? source, string? error, Location? location)
        {
            HintName = hintName;
            Source = source;
            Error = error;
            Location = location;
        }
        public string HintName { get; }
        public string? Source { get; }
        public string? Error { get; }
        public Location? Location { get; }
        public bool Equals(Result other) => HintName == other.HintName && Source == other.Source &&
            Error == other.Error && Equals(Location, other.Location);
        public override bool Equals(object? obj) => obj is Result other && Equals(other);
        public override int GetHashCode() => HintName.GetHashCode();
    }
}
