<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>$(TargetFrameworkVersion)</TargetFramework>
        <GenerateDocumentationFile>$(DocumentationFileFlag)</GenerateDocumentationFile>
        <RootNamespace>Fodot.Async</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <Compile Include="Event.fs" />
        <Compile Include="GD.fs" />
        <Compile Include="Signal.fs" />
        <Compile Include="Tween.fs" />
        <Compile Include="AsyncScene.fs" />
        <Compile Include="AsyncNode.fs" />
    </ItemGroup>
    
    <ItemGroup>
        <ProjectReference Include="..\Fodot\Fodot.fsproj" />
    </ItemGroup>

</Project>
