<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>$(TargetFrameworkVersion)</TargetFramework>
        <GenerateDocumentationFile>$(DocumentationFileFlag)</GenerateDocumentationFile>
        <RootNamespace>Moon</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <Compile Include="Interface\IFlipInit.fs" />
        <Compile Include="Interface\IPlatformShape.fs" />
        <Compile Include="Module\Flip.fs" />
        <Compile Include="Module\Action.fs" />
        <Compile Include="Module\Node.fs" />
        <Compile Include="Module\CanvasItem.fs" />
        <Compile Include="Library\NodePool.fs" />
        <Compile Include="Library\Recorder2D.fs" />
        <Compile Include="Library\Recorder3D.fs" />
        <Compile Include="Library\PhysicsQuery.fs" />
        <Compile Include="Library\PhysicsQueryResult.fs" />
        <Compile Include="Library\PhysicsState.fs" />
        <Compile Include="Library\PhysicsQueryPoint.fs" />
        <Compile Include="Library\PhysicsQueryRaycast.fs" />
        <Compile Include="Library\PhysicsQueryShape.fs" />
        <Compile Include="CSharp.fs" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Fodot.Module\Fodot.Module.fsproj" />
      <ProjectReference Include="..\Fodot.Async\Fodot.Async.fsproj" />
      <ProjectReference Include="..\Fodot.Extend\Fodot.Extend.fsproj" />
      <ProjectReference Include="..\Moon.Utils\Moon.Utils.fsproj" />
    </ItemGroup>

</Project>
