<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>$(TargetFrameworkVersion)</TargetFramework>
        <GenerateDocumentationFile>$(DocumentationFileFlag)</GenerateDocumentationFile>
        <RootNamespace>Fodot.Test</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <Compile Include="Test.fs" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Fodot.Async\Fodot.Async.fsproj" />
    </ItemGroup>

</Project>
