<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>$(TargetFrameworkVersion)</TargetFramework>
        <GenerateDocumentationFile>$(DocumentationFileFlag)</GenerateDocumentationFile>
        <RootNamespace>Fodot.Module</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <Compile Include="Vector2.fs" />
        <Compile Include="Color.fs" />
        <Compile Include="Transform2D.fs" />
        <Compile Include="CanvasItem.fs" />
        <Compile Include="Tween.fs" />
        <Compile Include="Node.fs" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Fodot\Fodot.fsproj" />
    </ItemGroup>

</Project>
