<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>$(TargetFrameworkVersion)</TargetFramework>
        <GenerateDocumentationFile>$(DocumentationFileFlag)</GenerateDocumentationFile>
        <RootNamespace>Fodot</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <Compile Include="Library.fs"/>
    </ItemGroup>

</Project>
