<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>$(TargetFrameworkVersion)</TargetFramework>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <RootNamespace>FSharp</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <Compile Include="Concurrent\Dict.fs" />
        <Compile Include="Concurrent\Queue.fs" />
        <Compile Include="Concurrent\Stack.fs" />
        <Compile Include="Concurrent\Bag.fs" />
        <Compile Include="Extend\ReLazy.fs" />
        <Compile Include="Extend\WeakMap.fs" />
        <Compile Include="Extend\Dict.fs" />
        <Compile Include="Extend\Queue.fs" />
        <Compile Include="Extend\Stack.fs" />
        <Compile Include="Extend\List.fs" />
        <Compile Include="Extend\Seq.fs" />
        <Compile Include="Builder.fs" />
    </ItemGroup>

</Project>
