<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>$(TargetFrameworkVersion)</TargetFramework>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <RootNamespace>FSharp</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <Compile Include="Concurrent\Dict.fs" />
        <Compile Include="Concurrent\Queue.fs" />
        <Compile Include="Concurrent\Stack.fs" />
        <Compile Include="Concurrent\Bag.fs" />
        <Compile Include="Generic\Dict.fs" />
        <Compile Include="Generic\Queue.fs" />
        <Compile Include="Generic\Stack.fs" />
        <Compile Include="Generic\List.fs" />
        <Compile Include="Generic\Seq.fs" />
        <Compile Include="Extend\ReLazy.fs" />
        <Compile Include="Extend\WeakMap.fs" />
        <Compile Include="Threading\Task.fs" />
        <Compile Include="Threading\Event.fs" />
        <Compile Include="Option.fs" />
        <Compile Include="Builder.fs" />
        <Compile Include="CSharp.fs" />
    </ItemGroup>

</Project>
