using System;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Godot.Node.Generator;

[Generator(LanguageNames.CSharp)]
public sealed class NodeGetGenerator : IIncrementalGenerator
{
    private static readonly DiagnosticDescriptor InvalidDeclaration = new(
        "NODEGET001", "Invalid NodeGet declaration", "{0}", "NodeGet",
        DiagnosticSeverity.Error, isEnabledByDefault: true);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static output => output.AddSource(
            "NodeGetAttribute.g.cs", """
            // <auto-generated />
            #nullable enable
            namespace Godot
            {
                /// <summary>Implements a cached GetNode getter. The default path is %PropertyName.</summary>
                [global::System.AttributeUsage(global::System.AttributeTargets.Property, AllowMultiple = false, Inherited = false)]
                internal sealed class NodeGetAttribute : global::System.Attribute
                {
                    public NodeGetAttribute() { }
                    public NodeGetAttribute(string path) { Path = path; }
                    public string? Path { get; }
                }
            }
            """));

        var properties = context.SyntaxProvider.ForAttributeWithMetadataName(
            "Godot.NodeGetAttribute",
            static (node, _) => node is PropertyDeclarationSyntax,
            static (attribute, _) => Create(attribute));

        context.RegisterSourceOutput(properties, static (output, result) =>
        {
            if (result.Error is not null)
                output.ReportDiagnostic(Diagnostic.Create(InvalidDeclaration, result.Location, result.Error));
            else
                output.AddSource(result.HintName, result.Source!);
        });
    }

    private static Result Create(GeneratorAttributeSyntaxContext context)
    {
        var syntax = (PropertyDeclarationSyntax)context.TargetNode;
        var property = (IPropertySymbol)context.TargetSymbol;
        Result Error(string message) => new("", null, message, syntax.GetLocation());

        if (!syntax.Modifiers.Any(SyntaxKind.PartialKeyword) || property.IsStatic || property.IsIndexer ||
            property.ReturnsByRef || property.ReturnsByRefReadonly || property.ExplicitInterfaceImplementations.Length > 0 ||
            syntax.Modifiers.Any(m => m.IsKind(SyntaxKind.AbstractKeyword) || m.IsKind(SyntaxKind.ExternKeyword)) ||
            syntax.ExpressionBody is not null || syntax.Initializer is not null ||
            syntax.AccessorList is null || syntax.AccessorList.Accessors.Count != 1 ||
            !syntax.AccessorList.Accessors[0].IsKind(SyntaxKind.GetAccessorDeclaration) ||
            syntax.AccessorList.Accessors[0].Body is not null || syntax.AccessorList.Accessors[0].ExpressionBody is not null)
            return Error("NodeGet requires an instance partial property with only 'get;' and no implementation.");

        var node = context.SemanticModel.Compilation.GetTypeByMetadataName("Godot.Node");
        if (node is null || !IsNode(property.ContainingType, node) || !IsNode(property.Type, node) ||
            property.NullableAnnotation == NullableAnnotation.Annotated)
            return Error("NodeGet requires a Godot.Node-derived class and a non-nullable Godot.Node-derived property type.");

        var scopes = syntax.Ancestors().OfType<TypeDeclarationSyntax>().Reverse().ToArray();
        if (scopes.Any(scope => !scope.Modifiers.Any(SyntaxKind.PartialKeyword) || scope.Modifiers.Any(SyntaxKind.FileKeyword)))
            return Error("The containing type and all enclosing types must be partial and must not be file-local.");

        var fieldName = "__NodeGet_" + property.Name;
        if (property.ContainingType.GetMembers(fieldName).Length > 0)
            return Error($"The generated cache field '{fieldName}' conflicts with an existing member.");

        var attribute = context.Attributes[0];
        var path = "%" + property.Name;
        if (attribute.ConstructorArguments.Length > 0)
        {
            if (attribute.ConstructorArguments[0].Value is not string explicitPath)
                return Error("NodeGet path must be a non-null constant string.");
            path = explicitPath;
        }

        var typeName = property.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var builder = new StringBuilder("// <auto-generated />\n#nullable enable\n");
        if (!property.ContainingNamespace.IsGlobalNamespace)
            builder.Append("namespace ").Append(property.ContainingNamespace.ToDisplayString()).AppendLine(" {");
        foreach (var scope in scopes)
        {
            var kind = scope is RecordDeclarationSyntax record
                ? "record " + (record.ClassOrStructKeyword.IsKind(SyntaxKind.StructKeyword) ? "struct" : "class")
                : scope.Keyword.Text;
            builder.Append(string.Join(" ", scope.Modifiers.Select(m => m.Text))).Append(' ')
                .Append(kind).Append(' ').Append(scope.Identifier.Text).Append(scope.TypeParameterList?.ToString()).AppendLine(" {");
        }
        builder.Append("private ").Append(typeName).Append("? ").Append(fieldName).AppendLine(";");
        builder.Append(string.Join(" ", syntax.Modifiers.Select(m => m.Text))).Append(' ')
            .Append(typeName).Append(' ').Append(syntax.Identifier.Text).AppendLine(" {");
        builder.Append("get => ").Append(fieldName).Append(" ??= this.GetNode<").Append(typeName).Append(">(")
            .Append(SymbolDisplay.FormatLiteral(path, quote: true)).AppendLine(");\n}");
        foreach (var _ in scopes)
            builder.AppendLine("}");
        if (!property.ContainingNamespace.IsGlobalNamespace)
            builder.AppendLine("}");

        // Hex encoding avoids collisions between namespaces, nested types and escaped identifiers.
        var identity = property.ContainingType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat) + "." + property.Name;
        var hint = string.Concat(Encoding.UTF8.GetBytes(identity).Select(b => b.ToString("x2"))) + ".NodeGet.g.cs";
        return new Result(hint, builder.ToString(), null, null);
    }

    private static bool IsNode(ITypeSymbol type, INamedTypeSymbol node)
    {
        if (type is ITypeParameterSymbol parameter)
            return parameter.ConstraintTypes.Any(constraint => IsNode(constraint, node));
        for (var current = type as INamedTypeSymbol; current is not null; current = current.BaseType)
            if (SymbolEqualityComparer.Default.Equals(current, node))
                return true;
        return false;
    }

    // Successful pipeline values contain only strings, so unchanged declarations compare equal.
    private readonly struct Result : IEquatable<Result>
    {
        public Result(string hintName, string? source, string? error, Location? location)
        {
            HintName = hintName;
            Source = source;
            Error = error;
            Location = location;
        }
        public string HintName { get; }
        public string? Source { get; }
        public string? Error { get; }
        public Location? Location { get; }
        public bool Equals(Result other) => HintName == other.HintName && Source == other.Source &&
            Error == other.Error && Equals(Location, other.Location);
        public override bool Equals(object? obj) => obj is Result other && Equals(other);
        public override int GetHashCode() => HintName.GetHashCode();
    }
}
