<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>$(TargetFrameworkVersion)</TargetFramework>
        <GenerateDocumentationFile>$(DocumentationFileFlag)</GenerateDocumentationFile>
        <RootNamespace>Fodot</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\FSharp.Extend\FSharp.Extend.fsproj" />
        <ProjectReference Include="..\Fodot.Bridge\Fodot.Bridge.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Compile Include="Attribute.fs" />
        <Compile Include="Interface.fs" />
        <Compile Include="Logger.fs" />
        <Compile Include="Singleton.fs" />
        <Compile Include="GDThread.fs" />
        <Compile Include="WeakMeta.fs" />
        <Compile Include="Variant.fs" />
        <Compile Include="Callable.fs" />
        <Compile Include="GodotObject.fs" />
        <Compile Include="GD.fs" />
        <Compile Include="FScript.fs" />
        <Compile Include="Node.fs" />
        <Compile Include="PackedScene.fs" />
        <Compile Include="Library.fs" />
        <Compile Include="Engine.fs" />
    </ItemGroup>

</Project>
